// <auto-generated />
using System;
using BlazorQuestionarioServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorQuestionarioServer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220406205013_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BlazorAppTest.Shared.QuestionarioTest", b =>
                {
                    b.Property<string>("QuestionarioTestId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ArgomentiProxEvento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("EMail")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Track01Valutazione")
                        .HasColumnType("int");

                    b.Property<string>("Track01WorkshopTrackId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Track02Valutazione")
                        .HasColumnType("int");

                    b.Property<string>("Track02WorkshopTrackId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Track03Valutazione")
                        .HasColumnType("int");

                    b.Property<string>("Track03WorkshopTrackId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Track04Valutazione")
                        .HasColumnType("int");

                    b.Property<string>("Track04WorkshopTrackId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Track05Valutazione")
                        .HasColumnType("int");

                    b.Property<string>("Track05WorkshopTrackId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UtilitaInformazioniRicevute")
                        .HasColumnType("int");

                    b.Property<int>("ValutazioneQualitaGeneraleEvento")
                        .HasColumnType("int");

                    b.Property<string>("WorkshopId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QuestionarioTestId");

                    b.ToTable("QuestionarioTest");
                });
#pragma warning restore 612, 618
        }
    }
}
